.github/workflows/release-please.yml

I think this is right? We don't need to make releases or do the PRs here. 
https://github.com/google-github-actions/release-please-action

chore(ci): update release-please.yml

---

.github/renovate.json5
.github/workflows/renovate.yml
staging/devpod/devpod.spec

Configures Renovate using their recommended presets and creates a custom manager which detects the package versions from the spec files.

feat: configure renovate regex manager

---

.github/workflows/rpmlint.yml

Performs rpmlint on all spec files in the repository

feat(ci): Add rpmlint action to lint spec files

---

staging/devpod/devpod.spec

https://github.com/loft-sh/devpod/releases/tag/v0.5.18

chore: update DevPod

---

staging/devpod/devpod.spec

Add missing dummy changelog

---

staging/devpod/devpod.spec

Add debug_package

---

staging/gnome-shell-extension-supergfxctl-gex/gnome-shell-extension-supergfxctl-gex.spec

Adds package spec for supergfxctl gex

feat(staging): Spec for supergfxctl GNOME shell extension

---

staging/uupd/uupd.spec

feat: add uupd

---

staging/ghostty/ghostty.spec

Add Ghostty until flatpak is available

feat: Add Ghostty

---

ublue/brew/src/profile.d/brew-bash-completion.sh
ublue/brew/src/profile.d/brew.sh
ublue/brew/src/security/limits.d/30-brew-limits.conf
ublue/brew/src/systemd/01-homebrew.preset
ublue/brew/src/systemd/brew-setup.service
ublue/brew/src/tmpfiles.d/homebrew.conf
ublue/brew/src/vendor.fish
ublue/brew/ublue-brew.spec

This should just add all the integrations we need, sadly it still doesnt install homebrew directly.

feat(ublue, brew): add universal blue homebrew integration scripts

---

ublue/setup-services/src/bin/sb-key-notify
ublue/setup-services/src/skel/.config/autostart/sb-key-notify.desktop
ublue/setup-services/ublue-setup-services.spec

Compiles locally just fine! Les go!!!!

feat: add sbkey-notify script and autostart file

---

ublue/setup-services/ublue-setup-services.spec

This might help with polkit issues related to bad permissions. - Either way, best to use the %config macro for these files

fix user setup

---

ublue/bling/src/bling.fish
ublue/bling/src/bling.sh
ublue/bling/src/ublue-bling
ublue/bling/ublue-bling.spec

This should add support for `bluefin-cli` and `bazzite-cli` or whatever else someone else would like to do with just a single configuration line change

feat: add ublue-bling for bling-cli support

---

ublue/bling/ublue-bling.spec

Accidentally forgot to remove the ublue-motd reference there

fix(ublue, bling): fix motd typo

---

ublue/bling/ublue-bling.spec

I am so sorry I edit that one on my phone and forgot about this one :(

fix: another damn typo on the ublue-bling.

---

ublue/bling/src/bling.fish
ublue/bling/src/bling.sh
ublue/bling/ublue-bling.spec

This should allow us to install starship from brew instead of installing it on the images! Very nice. I also added some redundancy for images that might not have the new updates for bluefin-cli

feat(ublue, bling): add starship integration to bling source script

---

ublue/motd/src/ublue-changelog
ublue/motd/src/ublue-motd
ublue/motd/ublue-motd.spec

That way we get some fancy changelogs on our images!! Yay!

feat: add ublue-changelog script to ublue-motd package

---

bluefin/branding/bluefin-branding.spec
bluefin/branding/schemas/dconf/db/distro.d/02-bluefin-keybindings

Fixes: https://github.com/ublue-os/bluefin/issues/1958

feat(bluefin, schemas): launch alpaca with Ctrl+Alt+Backspace

---

ublue/fastfetch/src/ublue-bling-fastfetch
ublue/fastfetch/ublue-fastfetch.spec

Continuation of https://github.com/ublue-os/packages/pull/110, pretty much! Gotta make sure this is also not broken somehow

fix: add dconf theme fallback to ublue-fastfetch, too

---

staging/devpod/devpod.spec

Devpod has been having build failures since FOREVER now, I just fixed it an updated it to 0.6.8. Also made the spec a bit stricter to make sure everything works on newer versions for sure.

fix: update devpod and fix its build

---

ublue/fastfetch/src/ublue-bling-fastfetch
ublue/fastfetch/ublue-fastfetch.spec
ublue/motd/src/ublue-motd
ublue/motd/ublue-motd.spec

Works fine on achillobator, didnt test on GTS yet.

fix: weird quoting in ublue-motd and ublue-fastfetch fallbacks

---

ublue/recipes/src/Justfile
ublue/recipes/src/header.txt
ublue/recipes/src/recipes/apps.just
ublue/recipes/src/recipes/system.just
ublue/recipes/src/recipes/vms.just
ublue/recipes/ublue-recipes.spec

This is pretty much just a initial test about how we could handle this. The specfile is just copying everything from the justfiles in src and putting it into `/usr/share/ublue-os/recipes/recipes.just`. We need to change the approach somewhat to make this good enough to include on Bluefin/Aurora/Bazzite

feat: initial ublue-recipes package

---

staging/souk/souk.spec

Builds fine and seems to run fine.

feat: add initial souk spec

---

staging/souk/souk.spec

- **feat: add initial souk spec**
- **fix: copr build depends on git**

fix: souk spec depends on git

---

ublue/bling/src/bling.sh

This allows users to modify Atuin init flags while maintaining the default behaviour.

feat: Allow users to modify Atuin init flags

---

ublue/kcm_ublue/kcm_ublue.spec

This is a KDE module I've been developing to manage updates and rebase to different images / tags.

feat: add KDE Configuration Module

---

bluefin/branding/schemas/applications/documentation.desktop

For discoverability when searching

fix: add keywords to the docs icon

---

ublue/kcm_ublue/kcm_ublue.spec

Pulls in a fix for https://github.com/ublue-os/aurora/issues/197 and https://github.com/ledif/kcm_ublue/issues/6.

chore(deps): bump kcm_ublue to 0.5.4

---

ublue/kcm_ublue/kcm_ublue.spec

Fixes a bug with toggling updates. https://github.com/ledif/kcm_ublue/issues/10

chore: bump kcm_ublue to 0.5.5

---

README.md

Forgot to remove this from the README

docs: unnecessary remove copr notice

---

ublue/kcm_ublue/kcm_ublue.spec

* Rework NVIDIA / HWE options by @ledif in https://github.com/ledif/kcm_ublue/pull/16

chore: bump kcm_ublue to 0.5.7

---

bluefin/branding/bluefin-branding.spec
bluefin/branding/schemas/dconf/db/distro.d/01-bluefin-folders

Solves https://github.com/ublue-os/bluefin/issues/2209

Move Ignition, Impression, and Refine into Utilities folder

---

packages/ublue-os-luks/src/90-ublue-luks.conf
packages/ublue-os-luks/src/luks-disable-tpm2-autounlock
packages/ublue-os-luks/src/luks-enable-tpm2-autounlock
packages/ublue-os-luks/ublue-os-luks.spec

Very minor refactoring. Seems to be working just fine

feat(packages): add ublue-os-luks from `config`

---

.github/workflows/build-package.yml

Creates a workflow we can use to select required jobs in GHA

chore: add fan-in build-package workflow

---

packages/ublue-bling/src/ublue-bling
packages/ublue-bling/ublue-bling.spec

https://github.com/Homebrew/homebrew-bundle/pull/1630 removed this flag
Fixes: #263

fix(ublue-bling): remove --no-lock flag from brew bundle

---

packages/ublue-os-media-automount-udev/60-media-automount.rules
packages/ublue-os-media-automount-udev/is_in_fstab.sh
packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec

Add utility to automount non-removable disk partitions

feat: Add ublue-os-media-automount-udev

---

packages/ublue-os-media-automount-udev/is_in_fstab.sh
packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec

Add missing permissions and use 'exit' instead of 'return' in is_in_fstab.sh

fix(ublue-os-media-automount-udev): Add missing exec perms

---

.github/renovate.json5

This will pin us onto the digests of actions

chore: update renovate preset to best-practices

---

.github/workflows/build-package.yml

https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised

chore: switch to step-security/changed-files

---

.github/CODEOWNERS

The bazzite entry was badly formatted :P

fix: formatting on CODEOWNERS file

---

packages/bluefin/bluefin.spec

This fixes the recent problems we got on the bluefin builds on the COPR

fix(bluefin): bluefin-fonts brewfile not getting recognized

---

packages/aurora/aurora.spec
packages/bluefin/bluefin.spec

tested by building aurora, bluefin, bluefin-lts locally with my copr enabled

fix: only install aurora-logos on aurora

---

packages/aurora/aurora.spec

Bump the new versions of the package to get new wallpapers correctly

chore(aurora): bump versions to get new wallpaper correctly

---

staging/gnome-shell-extension-caffeine/gnome-shell-extension-caffeine.spec

Bumped version in spec file to 56

chore: update caffeine for fedora 42

---

packages/glorpfetch/glorpfetch.spec
packages/glorpfetch/src/glorpfetch.jsonc

Fixes the spawn date of the glorp

fix: fix glorps spawned on date

---

packages/bluefin/bluefin.spec
packages/bluefin/fastfetch/fastfetch.jsonc

Apparently we forgot to fix this on OG Bluefin

fix(bluefin,fastfetch): make sure forged date is right on composefs

---

.github/CODEOWNERS

adds aurora maintainers as codeowners for the packages/aurora/ packages

chore(aurora): add aurora maintainers as codeowners for aurora pkgs

---

packages/ublue-os-just/ublue-os-just.spec

Bump the spec so we get updated ujust recipes

chore(just): bump the spec

---

packages/bluefin/schemas/etc/dconf/db/distro.d/04-bluefin-logomenu-extension

Thanks to jade for the recommendation, this does look nicer indeed!

fix(logomenu): set icon to 20px

---

packages/aurora/aurora.spec
packages/aurora/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile

fix(aurora): fix kubernetes.Brewfile

---

packages/bluefin-readymade-config/bluefin-readymade-config.spec

fix: typo in bluefin-readymade-config package

---

packages/ublue-os-just/src/etc-distrobox/distrobox.ini
packages/ublue-os-just/ublue-os-just.spec

See https://github.com/ublue-os/toolboxes/pull/141

chore(just): move to new arch-toolbox tag

---

packages/ublue-brew/src/usr/lib/systemd/system/brew-upgrade.service
packages/ublue-brew/ublue-brew.spec

As discussed in https://github.com/ublue-os/bluefin/pull/2475#pullrequestreview-2815962073.

chore(ublue-brew): unlink gsettings

---

packages/ublue-setup-services/src/scripts/check-sb-key.sh

fix(motd): update secure boot url

---

.github/workflows/build-package.yml
staging/README.md
staging/dart/dart.spec
staging/helium-gtk-theme/helium-gtk-theme.spec
staging/hydrogen-icon-theme/hydrogen-icon-theme.spec
staging/libhelium/libhelium.spec
staging/readymade/readymade.spec
staging/sass/sass.spec
staging/taidan/taidan.spec

Removes our reliance on terra for this

feat: add readymade/taidan and their deps to staging

---

packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile

It's time, this tool is too good, let's just call this another one of our strong opinions. 😄

feat(brew): add chezmoi to bluefin-cli

---

packages/ublue-os-just/ublue-os-just.spec

This PR just added ujust completion generation for fish shell. Tested on my Bluefin machine should work.
Close https://github.com/ublue-os/packages/issues/459

feat(just): add fish ujust completion

---

aurora/fedora-logos/fedora-logos.spec

Bump the release version to include resized assets.

fix(aurora): bump package release to actually get resized wallpapers

---

staging/README.md
staging/bazaar/bazaar.spec

Also wrote down the reason we need both of the packages on staging

feat(staging): add `bazaar` package

---

staging/bazaar/bazaar.spec

Fixes the search bar not working on bazaar

chore(bazaar): bump to 70ccb329667a4d90662e7ec556b219b83f195023

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/etc/dconf/db/distro.d/02-bluefin-keybindings
packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

Adds the keybinding to `ctrl+alt+\`!

feat(bluefin): add search keybinding for bazaar

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

Signed-off-by: Tulip Blossom <tulilirockz@proton.me>

chore(bluefin-schemas): remove nonexistent custom5

---

staging/gnome-shell-extension-logo-menu/gnome-shell-extension-logo-menu.spec
staging/gnome-shell-extension-logo-menu/logos-entries.patch

Signed-off-by: Tulip Blossom <tulilirockz@proton.me>

chore(logo-menu): bump to 89e0e4d84b97e65f0787e195663090f157dd82ae and fix patch

---

packages/aurora/aurora.spec
packages/aurora/wallpapers/images/aurora-wallpaper-3/metadata.json

Adds a new wallpaper from Chandeleer to the Aurora Branding package.

feat(aurora): add new wallpaper

---

packages/bluefin/schemas/etc/profile.d/ramalama.sh

feat: alias rl to ramalama

---

staging/bazaar/bazaar.spec

fixes build failure
can be closed then https://github.com/ublue-os/packages/pull/635

chore(bazaar): add libsoup and json-glib deps, remove gvfs

---

packages/ublue-brew/ublue-brew.spec

fix(ublue-brew): add gcc to requires

---

packages/krunner-bazaar/krunner-bazaar.spec

chore(deps): update krunner-bazaar to 1.0.1

---

packages/krunner-bazaar/krunner-bazaar.spec

Pulls in [fix: preserve sort order from Bazaar](https://github.com/ublue-os/krunner-bazaar/pull/8).

chore(deps): update krunner-bazaar to 1.0.4

---

packages/krunner-bazaar/krunner-bazaar.spec

Pulls in some performance improvements.

chore(deps): update krunner-bazaar to 1.0.5

---

packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile

feat(brew): add bbrew

---

packages/bluefin/bluefin.spec

Bump specfile version for #746
https://github.com/ublue-os/packages/pull/746#issuecomment-3114314086

chore: bump specfile version

---

.github/workflows/lint-brewfiles.yml

Closes #758 
This action just checks the brewfiles without installing the dependencies.

feat(ci): add ci action for brewfiles lint

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/etc/xdg/mimeapps.list

feat(bluefin): set bazaar default for mimetype flatpakref

---

packages/bluefin/bluefin.spec

Signed-off-by: Tulip Blossom <tulilirockz@proton.me>

chore(bluefin): package bump for august

---

packages/ublue-bling/src/bling.fish

feat: Allow modifying atuin flags in bling.fish

---

packages/ublue-bling/ublue-bling.spec

Should have done this in the [earlier PR](https://github.com/ublue-os/packages/pull/780), but I didn't read the README :sweat_smile:

chore(ublue-bling): bump version

---

packages/bluefin/bluefin.spec

schemas(bluefin): bump bluefin gnome schemas

---

packages/krunner-bazaar/krunner-bazaar.spec

Pulls in
- https://github.com/ublue-os/krunner-bazaar/pull/25

chore(deps): update krunner-bazaar to 1.2.1

---

packages/aurora/aurora.spec
packages/aurora/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile

fixes https://github.com/ublue-os/aurora-docs/issues/157

fix(aurora): update kubernetes brewfile

---

packages/krunner-bazaar/krunner-bazaar.spec

Pulls in https://github.com/ublue-os/krunner-bazaar/pull/28

chore(deps): bump krunner-bazzar to 1.2.2
