.github/workflows/rpmlint.yml

The current action does not support defining multiple spec files (PR in progress), but rpmlint does allow you to point it at a directory and it will check all subdirectories recursively, which I have done here.  
Also made this workflow run only when there are changes to the .spec files, since these are the only thing checked by rpmlint.
Finally removed some unused permissions on the workflow, such as permissions to packages, since these were unused.

fix: cleanup rpmlint workflow

---

staging/rtl8814au/rtl8814au-kmod.spec
staging/rtl8814au/rtl8814au.spec

This PR adds two spec files to build akmods packages for the rtl8814au driver. I've been testing it with a `0846:9054 NetGear, Inc. Nighthawk A7000 802.11ac Wireless Adapter AC1900 [Realtek 8814AU]` and the driver appears to be working and the kernel modules aliases seem to update correctly when the akmods package builds and installs inside a distrobox container. I'm not totally sure how to get it into rpm-ostree for testing against the host though.
I've got it building in my [copr here](https://copr.fedorainfracloud.org/coprs/zerochill/akmods/).
I am new to using akmods for building, so let me know if anything looks wrong. I tried to follow some examples from the existing ublue-os akmods copr builds.

feat: add rtl8814au wifi driver

---

akmods/rtl8814au/rtl8814au-kmod.spec
akmods/rtl8814au/rtl8814au.spec
akmods/rtl88xxau/rtl88xxau-kmod.spec
akmods/rtl88xxau/rtl88xxau.spec

This adds the 88xxau drivers from aircrack-ng which works for Realtek RTL8812AU/21AU and RTL8814AU. I was able to verify that it is working and co-existing with the rtl8814au driver that is already merged.
I found a packaging error with the license file in the rtl8814au build, so I updated that so it downloads to a unique filename and fixed up some rpmlint errors.
Edit: Also this is up in [my copr](https://copr.fedorainfracloud.org/coprs/zerochill/akmods/packages/) for testing

feat: add rtl88xxau driver

---

akmods/xone/xone-kmod-common.spec
akmods/xone/xone-kmod.spec

Negativo17 updated their spec files on 2024-01-17 to use the latest snapshot from xone driver commit af5e344fb0203738c5892e295aa4f7138889393d
This was the "Allow repeated GIP announcements" commit.
A few newer commits adding GIP authentication are failing builds. So this is a copy of the spec files at known good build state and we can update when newer features build properly.

feat: add xone spec files from last known working build

---

ucore/sanoid.spec

- switch from version to release for ucore identification (build error)
- added `sandoid-prune.service` to installed file list (build error)
- corrected typo in changelog date (build warning)
- switch timer to `0/15` to match upstream debian packaging and docs

fix: cleanup sanoid.spec to build on COPR

---

.github/workflows/wolfi.yml
wolfi/bluefin-base.yaml
wolfi/bluefin-base/etc/bashrc
wolfi/bluefin-base/etc/profile.d/00-bluefin-cli-brew-firstrun.sh
wolfi/bluefin-base/etc/profile.d/bash_completion.sh
wolfi/bluefin-base/etc/profile.d/command-not-found-host-exec.sh
wolfi/bluefin-base/etc/profile.d/homebrew-env.sh
wolfi/bluefin-base/etc/profile.d/modern-unix.sh
wolfi/bluefin-base/etc/profile.d/zz-profile_sourced.sh
wolfi/bluefin-base/etc/starship.toml
wolfi/bluefin-base/root/.bash_profile
wolfi/bluefin-base/root/.bashrc
wolfi/bluefin-base/usr/share/fish/vendor_conf.d/00-bluefin-cli-brew-firstrun.fish
wolfi/bluefin-base/usr/share/fish/vendor_conf.d/bling.fish
wolfi/bluefin-base/usr/share/fish/vendor_conf.d/brew.fish
wolfi/bluefin-base/usr/share/fish/vendor_functions.d/fish_command_not_found.fish
wolfi/bluefin-base/usr/share/fish/vendor_functions.d/fish_title.fish
wolfi/ublue-base.yaml
wolfi/ublue-base/pinentry
wolfi/ublue-base/sudo

This PR adds rudimentary support for building Wolfi packages as well as metapackages for both Wolfi and Bluefin CLI images
This will need some refactoring in the future (namely automated package updates, isolating package resources, moving over to wolfictl, etc), but the core implementation works
Packages are uploaded as build artifacts to GitHub from where toolboxes will be able to retrieve the artifacts, resign the packages, and install them on the image

feat: Add initial support for building Wolfi packages

---

akmods/rtl8814au/rtl8814au-kmod.spec

Update `rtl8814au` to latest [commit](https://github.com/morrownr/8814au/commit/810573647b837d88c4191597a0ea6d226f69f64c) to hopefully fix the [akmods f40 asus builder](https://github.com/ublue-os/akmods/actions/runs/9085440841/job/24968777396)
Will likely need someone to kick the [COPR build](https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/package/rtl8814au-kmod)?
Potentially closes: ublue-os/akmods#185

chore: update srccommit in rtl8814au-kmod.spec

---

ucore/sanoid.spec

systemctl's were pointing to /usr/local/sbin/sanoid, when the package is installed at /usr/sbin/sanoid.

bug: fix path to sanoid in systemctl

---

ucore/sanoid.spec

Just a typo correction in the systemctl sanoid service file.

bug: correct typo in systemctl description

---

staging/devpod/devpod.spec

Solves https://github.com/ublue-os/bluefin/issues/1875
See https://github.com/rpm-software-management/rpm/issues/367

Workaround for missing build ids

---

staging/gnome-software/gnome-software.spec

Without strict need to declare removing `gnome-software-rpm-ostree` package in `main` image.
So makes modifications related to Gnome Software unified here.

chore: Disable rpm-ostree backend in Gnome Software

---

staging/gnome-shell-extension-supergfxctl-gex/gnome-shell-extension-supergfxctl-gex.spec

Use subs for %{SOURCE0} and %{version} instead of hard coding each

chore(supergfxctl-gex): Update spec to use substitutions

---

staging/gnome-shell-extension-supergfxctl-gex/gnome-shell-extension-supergfxctl-gex.spec

The archive is already fetched as it's defined as a source. This was redundant and erroneous, remove it

fix(supergfxctl-gex): Remove wget

---

staging/kf6-kio/kf6-kio.spec

Kinoite has moved to KDE Frameworks 6.8. This override is stuck on 6.7, which is causing issues with some KDE utilities such as `kde-open`. See https://github.com/ublue-os/bluefin/issues/2001.

chore: update KIO 6.7 -> 6.8

---

.github/renovate.json5
staging/kf6-kio/kf6-kio.spec

Part of #53. This PR adds a Renovate rule for the `kf6-kio` package that automatically pulls the latest version info from Fedora 41's update stream.
I manually tested it on a self-hosted Gitea instance. In the screenshots below, I rolled back the version from 6.8 to 6.7 for testing and the renovate bot was able to recognize that it was behind a version and open a PR.

feat(renovate): Add rule for kf6-kio

---

staging/gnome-shell-extension-gsconnect/gnome-shell-extension-gsconnect.spec
staging/rpm-ostree/rpm-ostree.spec

- **feat(renovate, staging): rpm-ostree automation**
- **feat(renovate, staging): gsconnect automation**

feat: renovate for rpm-ostree and gsconnect

---

.github/renovate.json5
.github/test/renovate/test_renovate.py
staging/gnome-shell-extension-gsconnect/gnome-shell-extension-gsconnect.spec

This PR fixes a few issues with recently added renovate rules and adds tests for those rules to verify that they're working correctly.
The versioning scheme for `rpm-ostree` is different from the standard rpm version scheme as seen in packages such as `fwupd`. For example, compare `rpm-ostree 2024.9` vs `fwupd 1.9.27`. We need to add a package-specific rule for `rpm-ostree` that uses this date-based versioning scheme.
The github-releases rule we have defaults to a `semver` versioning scheme which requires at least a major and minor version component (e.g., `58.1`). The `GSConnect` versioning scheme only uses a single major version (e.g., `58`) which is more accurately captured by using the `semver-major` versioning scheme.
The newly added test cases confirm that the current rules as …

fix(renovate): update rules for rpm-ostree and gsconnect

---

akmods/new-lg4ff/new-lg4ff-kmod.spec
akmods/new-lg4ff/new-lg4ff.spec

adds spec files for [new-lg4ff](https://github.com/berarma/new-lg4ff) which enhances the `hid-logitech` kernel driver
Because the upstream driver will be loaded before this it will need to be blacklisted, however most people won't need this driver and while the lg4ff code in linux hasn't seen any real changes over the last years it might always receive changes that will not be present in the module so its best put behind a config or ujust script

feat: add new-lg4ff spec files

---

.github/test/renovate/test_renovate.py

This test confirms that a new minor version would indeed be picked up by renovate.
```bash
❯❯ just test-local
Working in /tmp/tmp.9qvNJjHV84
DEBUG: Using RE2 regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /usr/src/app/.github/renovate.json5
DEBUG: Converting GITHUB_COM_TOKEN into a global host rule
DEBUG: File config
[ ... snip ...]
Packages with updates:
{'loft-sh/devpod', 'rpm-ostree', 'ublue-os/uupd', 'sched-ext/scx', 'GSConnect/gnome-shell-extension-gsconnect', 'fwupd', 'kf6-kio', 'topgrade-rs/topgrade'}
passed
```

feat: add uupd to renovate tests

---

.github/test/renovate/test_renovate.py
staging/uupd/uupd.spec

Because the versioning scheme of uupd was inconsistent in terms of how strictly it followed semver (i.e., 0.5 -> 0.5.1 -> 1.0.0), the latest renovate job on [Mend](https://developer.mend.io/github/ublue-os/packages/-/job/019400e8-8c07-713b-8fdb-a81be311b230) did not pick up the new version for uupd.
Now that the versioning scheme is following semver, hopefully renovate will be able to automatically detect these updates after manually bumping the version to a semver-compliant value of 1.0.0.

chore: manually bump uupd version to 1.0.0

---

staging/uupd/uupd.spec

COPR failed building during go build because it depends on git somehow

fix(uupd): spec depends on git

---

bluefin/branding/bluefin-branding.spec

This seems to generate no more errors locally: ![image](https://github.com/user-attachments/assets/6a381c7e-f9ff-4c27-ad4e-7259f0352f6c)
Sadly forgot to add this on the last commit

fix(bluefin, branding): build fails due to missing icons entry on faces

---

ublue/motd/src/themes/blue.json
ublue/motd/src/themes/green.json
ublue/motd/src/themes/orange.json
ublue/motd/src/themes/pink.json
ublue/motd/src/themes/purple.json
ublue/motd/src/themes/red.json
ublue/motd/src/themes/slate.json
ublue/motd/src/themes/teal.json
ublue/motd/src/themes/yellow.json
ublue/motd/src/ublue-motd
ublue/motd/ublue-motd.spec

This should make it possible to share the ublue-motd script as a package for all the images: it should also be extensible through a configuration file so that we dont need to have a separate script for each thing. This is the first release so I just tried to make it equal to the old one.

feat: add ublue-motd as a standalone script

---

ublue/fastfetch/src/ublue-bling-fastfetch
ublue/fastfetch/src/ublue-fastfetch
ublue/fastfetch/src/vendor.fish
ublue/fastfetch/src/vendor.sh
ublue/fastfetch/ublue-fastfetch.spec

Should work identically to our existing fastfetch scripts. Builds and works fine on Achillobator.

feat: add ublue-fastfetch package for shared fastfetch configuration

---

ublue/setup-services/src/polkit/20-privileged-user.rules
ublue/setup-services/src/polkit/org.ublue.privileged.user.setup.policy
ublue/setup-services/src/profile/sbkey-notify-autostart.sh
ublue/setup-services/src/scripts/check-sb-key.sh
ublue/setup-services/src/scripts/ublue-privileged-setup
ublue/setup-services/src/scripts/ublue-system-setup
ublue/setup-services/src/scripts/ublue-user-setup
ublue/setup-services/src/services/check-sb-key.service
ublue/setup-services/src/services/ublue-system-setup.service
ublue/setup-services/src/services/ublue-user-setup.service
ublue/setup-services/ublue-setup-services.spec

This is still not the best implementation, but it makes it so the images can put their stuff in /usr/share/ublue-os/user-setup.hooks.d instead of putting them all over the place like they are doing right now.
It also implements the secure boot checking here ootb!

feat: add universal blue services for privileged and system setup

---

ublue/fastfetch/src/ublue-fastfetch
ublue/fastfetch/ublue-fastfetch.spec

If we let the find command see directories, the fastfetch sometimes will select the "symbols" folder during shuffling, making the logo default to the CentOS/Fedora logo.

fix(ublue, fastfetch): make fastfetch only see files

---

ublue/setup-services/src/scripts/check-sb-key.sh
ublue/setup-services/ublue-setup-services.spec

COPR build was failing because it was missing systemd-rpm-macros. I didnt even know this was on my local environment! Damn!
I also let the secureboot checker get disabled if we dont want it to work like on Achillobator right now

fix: COPR build for ublue-setup-services + allow sb-check-key to be disabled

---

ublue/brew/ublue-brew.spec

Needed so that https://github.com/ublue-os/bluefin/pull/2135 can get merged without modifications to ublue-os-just

fix: ghost brew.sh file so that ublue-brew is installable on aurora/bluefin ootb

---

staging/kf6-kio/kf6-kio.spec

Not sure why renovate didn't pick up this change.

chore: bump kf6-kio to 6.10

---

ublue/bling/src/bling.sh

It seems the intent was to source the file that we checked exists.
The file under the homebrew prefix is still sourced two lines below.

fix: typo in bling.sh

---

ublue/setup-services/src/scripts/ublue-user-setup
ublue/setup-services/ublue-setup-services.spec

Letting the image handle script versioning is the only way we can reliably do versioning per-script, otherwise they will either all run, or none will ever run

fix: make ublue-user-setup not handle versioning

---

ublue/setup-services/src/scripts/ublue-user-setup
ublue/setup-services/ublue-setup-services.spec

Without this the privileged part will run on every boot. Thats absolutely we dont want to happen. Privileged user setup should be handled by image scripts too

fix: make privileged setup not run all the time

---

ublue/setup-services/src/user-services/ublue-user-setup.service
ublue/setup-services/ublue-setup-services.spec

This should make it so they run when the desktop is about to run instead of in a random init process during plymouth. Should make it so things like privileged-setup works without artificial delays

  fix(setup-services): make it so the services run when graphical.target runs

---

.github/workflows/build-package.yml
Justfile
ublue/bling/ublue-bling.spec

This adds a check to make sure that modified rpms (and their files) actually build before we push them to COPR

feat: add package building check on github actions

---

ublue/fastfetch/src/ublue-fastfetch
ublue/fastfetch/ublue-fastfetch.spec

Allow passing arguments to fastfetch, such as '-l none' for posting output online.

Update ublue-fastfetch to pass arguments to fastfetch

---

.github/workflows/builder.yml
ublue-builder/Containerfile
ublue-builder/mock-wrapper

This also fixes the weird context for the files on the container build

feat(ublue-builder): add github groups and make it much more verbose for debugging RPM failures

---

staging/kf6-kio/kf6-kio.spec

Aurora builds are broken because of this version change on fedora repos. Renovate didn't pick this up either :(

chore: Bump kf6-kio to 6.11

---

staging/kf6-kio/kf6-kio.spec

We are missing this line compared to the spec in Fedora's official package.
```bash
diff \
<(curl -L https://raw.githubusercontent.com/ublue-os/packages/refs/heads/main/staging/kf6-kio/kf6-kio.spec) \
<(curl -L https://src.fedoraproject.org/rpms/kf6-kio/raw/rawhide/f/kf6-kio.spec)
```
```diff
< %global stable_kf6 stable
< 
< # renovate: datasource=yum repo=fedora-41-x86_64-updates pkg=kf6-kio
< %global majmin_ver_kf6 6.11
< 
9,10c4,5
< Version: %{majmin_ver_kf6}.0
< Release: 2%{?dist}.switcheroo.{{{ git_dir_version }}}
---
> Version: 6.11.0
> Release: 1%{?dist}
30,31d24
< # https://invent.kde.org/frameworks/kio/-/merge_requests/1556
< Patch201: 1556.patch
191a185
> %{_kf6_plugindir}/kio_dnd/
```

fix(kf6-kio): add missing plugins from upstream spec

---

ublue-builder/mock-wrapper

This fixes https://github.com/ublue-os/packages/pull/174, allows the package maintainer to not build for all packages and specifically build for some without the package breaking

fix(ublue-builder): skip building when package doesnt match architecture

---

ublue/brew/src/systemd/brew-setup.service
ublue/brew/ublue-brew.spec

This fixes a race condition where the brew home folder isnt created, usually because of people using shared home directories. This should make it so /home/linuxbrew is created before copying the contents of the brew tarball, thus users should always have the `/home/linuxbrew/.linuxbrew` folder applied properly

fix(ublue-brew): make setup service always create the linuxbrew folder before setting up brew

---

.github/workflows/brew-tarball.yml
.gitignore
Justfile

Should release a homebrew tarball weekly!

feat: add homebrew tarball generating action

---

ublue/brew/ublue-brew.spec

COPR is currently failing because its trying to reference a aarch64 brew tarball that does not exist right now.

fix(ublue-brew): make COPR not fail on sourcing aarch64 homebrew tarball

---

Justfile

This makes the generated tarball not fail when getting extracted by GNU tar on the brew-setup service. It also makes the tarball slightly smaller for some reason

fix: ensure homebrew tarball is generated with GNU utilities

---

.github/workflows/brew-tarball.yml

We need to rebuild it and I forgot to add this to the action

ci(brew-tarball): allow releasing tarballs via workflow dispatch

---

ublue/brew/ublue-brew.spec

We need the automatic spec bumping action to get renovate to bump it properly - this should do it for now
The github actions workflow is still going to complain for now

chore: bump release referenced by ublue-brew

---

ublue/motd/src/ublue-changelog
ublue/motd/ublue-motd.spec

ublue-changelogs crashed on my system telling me that there was no themes directory, this should fix it as we didnt apply the dconf/gsettings accent color workaround for ublue-changelogs still

fix(ublue-motd): make sure that dconf has a fallback for the accent color theme

---

ublue/rebase-helper/src/ublue-dx-helper
ublue/rebase-helper/src/ublue-rebase-helper
ublue/rebase-helper/ublue-rebase-helper.spec

Manually tested this locally and it seems to be working perfectly fine on Bluefin LTS. This should remove the need to have a rebase script for each image.

feat(ublue-rebase-helper): add ublue-rebase helper and ublue-dx-helper

---

packages/ublue-os-just/ublue-os-just.spec

this helps in situations like using this on CentOS based Bluefin-LTS where powerstat isn't in EPEL yet.

feat: powerstat should be recommended not required

---

.github/workflows/build-package.yml
packages/ublue-motd/ublue-motd.spec

This will make it so multiple artifacts from different packages wont collide in naming, basically allows PRs with multiple spec files being modified to work just fine on CI

ci: make sure artifacts are unique per package

---

packages/ublue-polkit-rules/src/org.debian.pcsc-lite.access_card.rules
packages/ublue-polkit-rules/ublue-polkit-rules.spec

Port from https://github.com/ublue-os/config/pull/231. Adds a package specifically for polkit rules we might want.
Fixes: #209

feat(ublue-polkit-rules): add polkit rules for yubikeys

---

packages/ublue-os-just/ublue-os-just.spec
packages/ublue-os-luks/ublue-os-luks.spec
packages/ublue-os-signing/ublue-os-signing.spec
packages/ublue-os-udev-rules/ublue-os-udev-rules.spec
packages/ublue-os-update-services/ublue-os-update-services.spec

Afaik this needs to be agreed upon by all the contributors for those packages. Better to PR this earlier than later at least.
Fixes: #217

chore: move all ublue-os packages to Apache-2.0

---

packages/ublue-os-just/src/recipes/50-akmods.just
packages/ublue-os-just/ublue-os-just.spec

Direct port from https://github.com/ublue-os/config/pull/350. This fixes the wl module getting disabled incorrectly due to the wrong directory being used for the modprobe configuration

 fix(just): incorrect config files in configure-broadcom-wl

---

packages/ublue-os-just/src/recipes/60-custom.just
packages/ublue-os-just/ublue-os-just.spec

Makes 60-custom.just an optional import, and remove the default one.  
This allows bluefin-lts to COPY the custom justfile without it being overwritten by the ublue-os-just install.
Optional imports are documented [here](https://github.com/casey/just#:~:text=Imports%20may%20be,foo/bar.just%27).

fix(ublue-os-just): make 60-custom.just an optional import

---

packages/ublue-setup-services/src/lib/libsetup.sh
packages/ublue-setup-services/ublue-setup-services.spec

This will allow us, on downstreams, to version scripts much easier because we can just use a single function that will allow/disallow running the hooks on version changes
```sh
#!/usr/bin/env bash
source ./libsetup.sh
version-script test user 1 || exit 0
echo "works first time"
```
This should only output "works first time" at the first time the script is ran

feat: add helper script for ublue-setup-scripts on downstreams

---

packages/ublue-setup-services/src/scripts/ublue-privileged-setup
packages/ublue-setup-services/src/scripts/ublue-system-setup
packages/ublue-setup-services/src/scripts/ublue-user-setup
packages/ublue-setup-services/src/user-services/ublue-user-setup.service
packages/ublue-setup-services/ublue-setup-services.spec

The `Condition=!@system` stuff I got straight from https://github.com/ublue-os/bluefin/pull/2199. These should make it so the scripts _actually run_ instead of accidentally running `bash script1.sh script2.sh`

fix(ublue-user-setup): make privileged/user/system scripts run + ensure systemd service is run only by human users

---

packages/ublue-setup-services/src/lib/libsetup.sh
packages/ublue-setup-services/src/services/ublue-system-setup.service
packages/ublue-setup-services/src/user-services/ublue-user-setup.service
packages/ublue-setup-services/ublue-setup-services.spec

This ensures that the graphical-session target will not get locked up if something makes the ublue-user-setup/system-setup services break for whatever reason. The locking mechanism is also not very useful as it just brings more ways for the services to get permanently stuck, and it doesnt even help out that much with multiple scripts modifiying the version state

fix(ublue-setup-services): use simple type for service + remove locking

---

packages/ublue-setup-services/src/polkit/20-privileged-user-setup.rules
packages/ublue-setup-services/src/polkit/20-privileged-user.rules
packages/ublue-setup-services/src/polkit/org.ublue.privileged.user.setup.policy

Made this into a single PR since this is necessary for the stuff to work on Bluefin LTS + having two PRs makes it so it conflicts and acks get dismissed.
Testing this should be just: `cp (rules) /etc/polkit-1/rules.d/oldrules-i-forgot && systemctl restart polkit` for the polkit rules.

fix(ublue-setup-services): allow privileged setup to be executed by wheel group without password

---

.github/workflows/brew-tarball.yml

We have lots more releases than we should. This should limit the homebrew tarball building just to weekly builds

ci: force homebrew tarball to only build weekly, and not on pull request

---

.gitignore
Justfile

This will allow us to test packages easier and in a persistent manner via `systemd-sysext` by automatically creating layers based on the selected RPMs. This _REQUIRES_ systemd 257 as before that we didnt get the selinux patch for sysext. This sets selinux contexts automatically for the RPMs too so they should be able to mount/run just fine by default
The expected workflow is:
- just build (specfile)
- just overlay ./mock/(chroot)/results/(my rpm).rpm

feat(justfile): add overlay recipe with sysext for testing

---

packages/ublue-os-media-automount-udev/99-media-automount.rules
packages/ublue-os-media-automount-udev/is_in_fstab.sh
packages/ublue-os-media-automount-udev/media-automount.conf
packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec

- **fix(ublue-os-media-automount-udev): Dont error out in is_in_fstab.sh**
- **fix(ublue-os-media-automount-udev): Load rule the latest and fetch UUID with lsblk**
- **fix(ublue-os-media-automount-udev): Only mount labeled partitions**
- **fix(ublue-os-media-automount-udev): Add missing mount options to btrfs partitions**
- **fix(ublue-os-media-automount-udev): Add /run/media/media-automount symlink for compatibility**
- **chore(ublue-os-media-automount-udev): Use systemd-rpm-macros**

feat: fully functional media-automount

---

packages/ublue-bling/src/ublue-bling

This PR adds a link to the bling-cli documentation right after bling is activated, helping users access more information about its usage.

docs: Add documentation link after enabling bling

---

packages/ublue-os-just/src/lib-ujust/libformatting.sh

`\033[22m` is the correct ANSI code to unset bold mode (and faint/dim mode); `\033[21m` disables bold mode in some terminals but enables double-underline in others (for reference: https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797). I also changed `\e` to `\033` in the clickable hyperlink helper function because that's more widely compatible.

Fix ANSI code for unbold formatting; \e -> \033 for compatibility.

---

packages/ublue-brew/src/systemd/01-homebrew.preset
packages/ublue-brew/src/systemd/brew-update.service
packages/ublue-brew/src/systemd/brew-update.timer
packages/ublue-brew/src/systemd/brew-upgrade.service
packages/ublue-brew/src/systemd/brew-upgrade.timer
packages/ublue-brew/ublue-brew.spec

These services and timers are taken directly from Aurora, with the exception of adding the unlink logic from https://github.com/ublue-os/packages/issues/269#issuecomment-2728550758 to `brew-upgrade.service`.
Closes #269.

feat(ublue-brew): add update/upgrade services and timers

---

packages/kcm_ublue/kcm_ublue.spec

* fix: rework notify-send to not use systemd-run by @ledif in https://github.com/ledif/kcm_ublue/pull/17
**Full Changelog**: https://github.com/ledif/kcm_ublue/compare/v0.5.7...v0.5.8

chore(kcm_ublue): bump version to 0.5.8

---

.github/workflows/build-package.yml

Its a good idea but its causing more trouble than not right now. We can maybe use this again at some point when we make sure this is more "standard" across all repos

revert: remove the safe-to-run tag

---

packages/ublue-os-signing/src/etc/pki/containers/ublue-os-backup.pub
packages/ublue-os-signing/src/usr/etc/containers/policy.json
packages/ublue-os-signing/ublue-os-signing.spec

Closes https://github.com/ublue-os/main/issues/703
These keys will be unused until a time when we need to rotate.  When we do need to rotate, we can change the priv key in GitHub Actions, and these will be accepted by the signing policy.

chore: create backup container signing keys

---

packages/ublue-brew/ublue-brew.spec

The build is failing in copr because I forgot to include the `.timer` unit files in the `install` section:
```bash
RPM build errors:
error: File not found: /builddir/build/BUILD/ublue-brew-0.1.3-build/BUILDROOT/usr/lib/systemd/system/brew-update.timer
error: File not found: /builddir/build/BUILD/ublue-brew-0.1.3-build/BUILDROOT/usr/lib/systemd/system/brew-upgrade.timer
File not found: /builddir/build/BUILD/ublue-brew-0.1.3-build/BUILDROOT/usr/lib/systemd/system/brew-update.timer
File not found: /builddir/build/BUILD/ublue-brew-0.1.3-build/BUILDROOT/usr/lib/systemd/system/brew-upgrade.timer
```
> Source: https://download.copr.fedorainfracloud.org/results/ublue-os/packages/fedora-41-x86_64/08863563-ublue-brew/builder-live.log.gz
I wonder why the CI did not catch this.

fix(ublue-brew): include missing timer units

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

This is the default on GNOME 48 afaik, we want this cuz its much better tbh

feat(bluefin): center new windows by default

---

packages/aurora/aurora.spec
packages/bluefin/bluefin.spec

Apparently I bumped the version wrong and the newer packages aren't being downloaded because they have lower or equal "NEVRA"
Someone on the fedora copr matrix suggested this to me.

chore: bump release field of aurofin

---

.github/renovate.json5
.github/workflows/builder.yml

This unblocks ublue-builder's latest builds since it fixes the container, it also changes the container to wolfi-base (just straight up better than using fedora in this case). And I also removed the container pinning on the github actions because we will always run into dumb stuff like this, some container getting pinned then the action breaking for a month or something

ci: remove container pinning on GHA from renovate config and use wolfi for ublue builder manifest action

---

ublue-builder/mock-wrapper

We werent getting any logs because when mock dies it just exited everything :P

fix(ublue-builder): make it so build logs get printed after mock failure

---

staging/gnome-shell-extension-searchlight/gnome-shell-extension-searchlight.spec

This also bumps search light to a version that supports G48
Builds fine locally

feat: add search light to staging copr here instead of kyle's repo

---

staging/gnome-shell-extension-logo-menu/gnome-shell-extension-logo-menu.spec

Fixes: https://github.com/ublue-os/bluefin/issues/2348
The logo install was being expanded before installing the framework and ampere logos so it didnt show up on the package

fix(staging,logomenu): make sure logos are getting included on logomenu's package

---

packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

This will only show up on the live ISO. Also cleans up old vestigial stuff.
Just to confirm, the readymade binary won't be on the final installed system right? We wouldn't want this showing up on existing systems.

feat: add readymade to favorites

---

packages/ublue-os-udev-rules/src/udev-rules.d/50-usb-realtek-net.rules
packages/ublue-os-udev-rules/ublue-os-udev-rules.spec

This reverts commit fc2583bea4d5c45f455f97d51bf464d2f9e8d989.
Requested by original PR contributor here:
https://github.com/ublue-os/packages/pull/374#issuecomment-2819057311

Revert "fix(ublue-os-udev-rules): update source of the Realtek 50-usb-realtek-net.rules file (#374)

---

packages/ublue-os-just/src/recipes/00-default.just

The grub one is bazzite-only and we don't want to support that anywhere else. We don't need a ujust for pulling in distrobox so clean that up.

fix(just): remove unused commands

---

packages/aurora/aurora.spec
packages/aurora/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile

This should fix the install-k8s-devtools brewfile when using the ujust to install these tools.

fix(aurora): Installation error when using kubernetes brewfile

---

packages/ublue-brew/src/systemd/brew-upgrade.service

User report from Discord that Nautilus wouldn't start because brew's Python was in their PATH.
https://discord.com/channels/1072614816579063828/1087140903031943178/1362410617780178994
```
~> which python3
/home/linuxbrew/.linuxbrew/bin/python3
~> python3 -c 'import gi; print(gi)'
<module 'gi' (namespace) from ['/home/linuxbrew/.linuxbrew/Cellar/python@3.13/3.13.3/lib/python3.13/site-packages/gi']>
```

fix: unlink python in brew-upgrade.service

---

packages/ublue-fastfetch/src/vendor.fish
packages/ublue-fastfetch/src/vendor.sh

The alias is unnecessary for people who don't know what hyfetch is while getting in the way of people who do know what hyfetch is and wish to use it.

ublue-fastfetch: remove alias for hyfetch

---

ublue-builder/mock-wrapper

This just makes it so if the build fails it actually fails instead of saying its ok

fix(ublue-builder): make failures be recognized as failures on the mock wrapper

---

packages/aurora/aurora.spec
packages/bluefin-readymade-config/bluefin-readymade-config.spec
packages/bluefin/bluefin.spec
packages/ublue-bling/ublue-bling.spec
packages/ublue-fastfetch/ublue-fastfetch.spec
packages/ublue-motd/ublue-motd.spec
packages/ublue-os-just/ublue-os-just.spec
packages/ublue-rebase-helper/ublue-rebase-helper.spec
packages/ublue-setup-services/ublue-setup-services.spec

This is more of a preparation for new architectures, this just tags all the `ublue-*`
packages as "noarch", so they arent architecture dependant since they already arent
(they are all just scripts). Also refactors a bit of a few packages to have better `install` statements

refactor: set arch to noarch for most `ublue-*` packages

---

staging/gnome-shell-extension-logo-menu/extension-boxbuddy.patch
staging/gnome-shell-extension-logo-menu/gnome-shell-extension-logo-menu.spec

This will just open up the local document on the Logomenu extension for the bluefin build :)

fix(logomenu): open up local PDF document

---

packages/ublue-brew/ublue-brew.spec

This makes it work on COPR, cuz they are using aarch64 builders for x86_64 packages

fix: ensure ublue-brew builds on hosts w/ different architectures from mock's runtime

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/etc/skel/.config/mimeapps.list

This PR makes the Papers Flatpak the default pdf viewer.
Fixes #428

chore: make Papers flatpak default for pdf

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/etc/skel/.config/mimeapps.list
packages/bluefin/schemas/etc/xdg/mimeapps.list

Since the `mimeapps.list` was placed in `/etc/skel/.config`, it only applied to new users. If we want the default app to be set for all users, it should be in `/etc/xdg`.
This file doesn't exist in Bluefin currently so there's no risk of overwriting an upstream Fedora file.
```bash
❯ podman run ghcr.io/ublue-os/bluefin:stable ls /etc/xdg
QtProject
Xwayland-session.d
autostart
menus
qtchooser
systemd
user-dirs.conf
user-dirs.defaults
❯ podman run ghcr.io/ublue-os/bluefin:stable cat /etc/xdg/mimeapps.list
cat: /etc/xdg/mimeapps.list: No such file or directory
```

fix(bluefin): move mimeapps.list to /etc/xdg

---

.github/workflows/build-package.yml
Justfile
ublue-builder/mock-wrapper

This makes it so `MOCK_REPOS` is a comma-separated list of repos that mock can use on ublue-builder, that way we finally have COPR support! Also adds some handling on the github actions part too
Tested it a bit, doesnt break when there are no COPRs, and makes it so everything works when there are COPRs. The only caveat is the weird handling that you need to do for the COPRs

feat(ublue-builder): add handling for external coprs

---

bluefin/fedora-logos/fedora-logos.spec
bluefin/fedora-logos/src/anaconda/fedora.css

We may have missed the CSS for fedora-logos package to find the update images.
This uses a CSS file from Aurora as is is known to work for their ISO and seems to map to our use case and images here, too. https://github.com/ublue-os/bluefin/blob/3bbcb7b98df817a5ebb4de4ee18d06a07289b826/spec_files/aurora/fedora-logos/fedora.css

fix: add CSS for bluefin anaconda branding

---

packages/ublue-os-just/ublue-os-just.spec

Close #518
This should be the easiest way: put `ujust.fish` in `/usr/share/fish/vendor_completions.d/`, which already exists in the atomic/main image, so no extra fish deps or mkdir hack.
https://github.com/fish-shell/fish-shell/commit/5157ac30faf8fde5e9ea84977fdf430e01b71f96

fix(just): fix fish completion file directory

---

packages/ublue-os-just/ublue-os-just.spec

this generates the ujust shell completion on build time instead of generating them on each client after every package installation in the `%post` step.
This has the benefit that the content is now actually tracked inside the rpm instead of essentially random files that are floating around the filesystem.
```
❯ rpm -qlp mock/fedora-42-x86_64/result/ublue-os-just-0.46-1.fc42.noarch.rpm
...
/usr/share/bash-completion/completions/ujust
/usr/share/fish/vendor_completions.d/ujust.fish
...
/usr/share/zsh/site-functions/_ujust
```
This also uses the proper respective rpm macros like `%{bash_completions_dir}`.

fix: generate ujust shell completions on build time

---

packages/aurora/aurora.spec
packages/aurora/fastfetch/fastfetch.jsonc
packages/bluefin/bluefin.spec
packages/bluefin/fastfetch/fastfetch.jsonc

Follows #490 
This hides the overlay fs that comes with composefs.
This requires fastfetch 2.44 ! (Currently 2.43 is available on fedoras repo)
The parameter is ignored if used with fastfetch 2.42 (I've successfully tested it)
Tested with fastfetch from brew 
`/home/linuxbrew/.linuxbrew/Cellar/fastfetch/2.44.0/bin/fastfetch --config packages/bluefin/fastfetch/fastfetch.jsonc`
And with fastfetch 2.41 (overlay appears but no errors)
`/usr/bin/fastfetch --config packages/bluefin/fastfetch/fastfetch.jsonc `

feat: Hide the overlay fs within fastfetch using the new hideFS param

---

staging/gnome-shell-extension-search-light/gnome-shell-extension-search-light.spec

We got the GNOME 48 backports for EL10 now!!! Should be fine building it with the patches :)

fix(search-light): enable gnome 48 patches for epel 10 builds

---

staging/bazaar/bazaar.spec

kde images (except bazzite, already happens to pull it in) don't ship with `gvfs` and would throw this error without it:
```
could not retrieve remote content: failed to download icon from uri https://dl.flathub.org/repo/logo.svg for remote 'flathub': GLib error: Operation not supported
```

fix(bazaar): add gvfs dependency

---

packages/ublue-setup-services/src/services/ublue-system-setup.service

Ensures that $HOME is set so libsetup doesn't complain about it being unbound

fix(ublue-setup-services): set service user as root

---

packages/aurora/aurora.spec

adds our white logo as the start-here logo that is used in the default configuration of
the KDE Plasma Panel. That value is only set on initial user login of
fedora kinoite, so this fixes the inconsistency that rebasers have the
purple logo instead of the white one.
For consistency with fedora-logos I put it in scalable/{apps,places}

feat(aurora): add start-here logo

---

staging/bazaar/bazaar.spec

libdex 0.10.1 breaks bazaar in VMs and low spec PCs
this centralizes https://github.com/ublue-os/aurora/pull/713 and respective PR to bluefin
this is probably what I should have done in the first place lol
This should fix bazaar assuming libdex doesn't get upgraded in the image build somewhere
```
sudo dnf5 repoquery --whatrequires libdex | grep -v "i686\|bazaar"
Updating and loading repositories:
Repositories loaded.
gnome-builder-0:48.0-1.fc42.x86_64
gnome-builder-0:48.2-1.fc42.x86_64
libdex-devel-0:0.10.1-1.fc42.x86_64
libdex-devel-0:0.9.1-1.fc42.x86_64
libdex-devel-docs-0:0.10.1-1.fc42.noarch
libdex-devel-docs-0:0.9.1-1.fc42.noarch
libsysprof-0:48.0-1.fc42.x86_64
sysprof-0:48.0-1.fc42.x86_64
sysprof-agent-0:48.0-1.fc42.x86_64
sysprof-cli-0:48.0-1.fc42.x86_64
```

fix(bazaar): explictly require libdex 0.9.1

---

packages/kcm_ublue/kcm_ublue.spec

Fixes https://github.com/ledif/kcm_ublue/issues/19.

chore: bump kcm_ublue to 0.6.0

---

packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile

Fixes syntax error in Brewfile for installing k8s dev tools (`ujust install-k8s-dev-tools`).

fix: syntax error k8s Brewfile

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

Gnome F48 now uses `Adwaita Sans` font as the default, this follows upstream.
Before merging, this requires installing either `adwaita-fonts` or only `adwaita-sans-fonts` in the bluefin repo. This is because it's bundled by default with F42 but we also need to take into account F41.
See https://blogs.gnome.org/monster/introducing-adwaita-fonts/

feat: Use the new Adwaita font instead of Inter

---

packages/aurora/aurora.spec
packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-ai.Brewfile

claude-code from brew doesn't really work properly in Linux

fix: remove claude-code from aurora-ai recipe

---

packages/aurora/aurora.spec
packages/aurora/kde-config/sddm/01-breeze-aurora/faces/.face.icon

I made a mistake with the filename in https://github.com/ublue-os/packages/pull/816, so the aurora logo doesn't show up in plymouth
stock sddm icon is ugly, so replacing that from breeze

fix(aurora): plymouth typo

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

This turns on bazaar as a search provider.

fix: add search provider and update GNOME settings

---

packages/bluefin/bluefin.spec
packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override

copilot says there should be no whitespaces here.

fix: formatting in gschema.override file

---

packages/ublue-bling/src/bling.sh
packages/ublue-bling/ublue-bling.spec

Issue #748 is solved by removing carapace from the brew list. This change also removes it from the bash/zsh source.

fix: remove carapace from ublue-bling

---

packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
packages/ublue-os-media-automount-udev/ublue-os-media-automount.py

Issue: certain partitions are mounted in my system while explicitly disabled in `fstab`.
I noticed in recent updates in Bazzite that partitions got mounted on boot that I had disabled in `fstab`. Further investigation revealed that this service is responsible. The current method with manually parsing `fstab` and then look up the filesystem with `findfs` fails when using certain identifiers. This method also seems a bit hacky and prone to errors. 
This leads to unexpected behavior where the different way a `fstab` entry can match with a partition does not always finds a match so the partition gets mounted anyway and possibly the wrong path.
I changed this to use 'findmnt' which will return the 'partuuid' for all of the fstab entries, regardless of how it's defined. `lsblk`  Also outputs …

fix(ublue-os-media-automount): match fstab entries by uuid

---

packages/aurora/aurora.spec
packages/aurora/schemas/usr/share/pipewire/pipewire.conf.d/raop.conf
packages/bluefin/bluefin.spec
packages/bluefin/schemas/usr/share/pipewire/pipewire.conf.d/raop.conf

Removes the default RAOP configuration from bluefin and aurora. 
Will require one approval from each project before merging.

fix: remove raop default config

---

packages/krunner-bazaar/krunner-bazaar.spec

KRunner-bazaar works fine with the flatpak.
Currently there would not be a way to not have bazaar rpm as it is a hard dependency.
This opens the door for [potentially having flatpak bazaar ](https://github.com/ublue-os/aurora/issues/948)(no rpm installed) + this plugin.
Doesn't change anything for bazzite and aurora as they don't rely on this behavior anyway.

fix(krunner-bazaar): make bazaar optional

---

packages/ublue-os-just/ublue-os-just.spec

`error: line 95: second %install`
https://github.com/ublue-os/packages/actions/runs/17774354184/job/51568633819?pr=899#step:5:2666
maybe older rpm versions are more strict about this?

fix(just): epel builds by removing rpm macros from changelogs
